# https://taskfile.dev

version: '3'

includes:
  pypi:
    taskfile: ./tasks/pypi.tasks.yml
    dir: .

vars:
  GREETING: Hello, World!

tasks:

  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  test:
    desc: _
    # md
    # > Run tests with task test
    #
    # - currently bonded env 
    # /md
    cmds:
      - task run-all:full -d tests
