# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  build:
    desc: _
    dir: ..
    cmds:
      - python setup.py sdist bdist_wheel
