version: '3.2'

networks:
  default:
    external: true
    name: ${DECK_DCL_NETWORK}

services:
  test-docker-101:
    image: ${DECK_DIMAGE_MAIN__IMAGE}
    environment:
      - RCLONE_CONFIG=/_confs/rclone.conf
    volumes: 
      - "../../confs/sample.rclone.conf/rclone.conf.guest-int-net.conf.toml:/_confs/rclone.conf"
    command: "bash -c 'cat /_confs/rclone.conf && rclone mkdir lms3:do-ob && rclone lsd lms3: | grep do-ob'"

  test-code-102:
    image: ${DECK_DIMAGE_MAIN__IMAGE}
    environment:
      - RCLONE_CONFIG=/src/confs/sample.rclone.conf/rclone.conf.guest-int-net.conf.toml
      - PYTHONPATH=/src
      - DECK_lms3_ENDPOINT=http://lms3:9000
    volumes: 
      - "../..:/src"
    command: "task run-all -d /src/tests"

  build-package-103:
    image: ${DECK_DIMAGE_MAIN__IMAGE}
    environment:
      - PYTHONPATH=/src
    volumes: 
      - "../..:/src"
    command: "task pypi:clean:pypi pypi:build:pypi -d /src"